all:
	rm -f ~/.bash_profile ~/.bashrc ~/etc/bash_prompt.bash
	ln -s `pwd`/.bash_profile ~/.bash_profile
	ln -s `pwd`/.bashrc ~/.bashrc
	mkdir -p ~/etc
	ln -s `pwd`/bash_prompt.bash ~/etc/bash_prompt.bash
